import { Inconsolata, Inter, Lora } from "next/font/google";
import "./globals.css";
import "./style.css";

import Navigation from "./components/navigation";

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dictionary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inconsolata.variable} ${inter.variable} ${lora.variable} text-neutral-800 antialiased px-6 md:px-10`}
      >
        <div className="lg:w-[65%] xl:w-[50%] mx-auto mt-6 mb-12 md:my-15">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
