import { cookies } from "next/headers";
import { Inconsolata, Inter, Lora } from "next/font/google";
import "./globals.css";
import "./style.css";

import Navigation from "./components/navigation";
import SearchBar from "./components/searchBar";

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dictionary",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const font = cookieStore.get("font")?.value || "sans";
  const theme = cookieStore.get("theme")?.value || "light"

  return (
    <html lang="en" data-font={font} className={theme}>
      <body
        className={`${inconsolata.variable} ${inter.variable} ${lora.variable} dark:bg-neutral-950 text-neutral-800 dark:text-neutral-0 antialiased px-6 md:px-10 transition duration-100 ease-out`}
      >
        <div className="lg:w-[65%] xl:w-[50%] mx-auto mt-6 mb-12 md:my-15">
          <Navigation savedFont={font} savedTheme={theme}/>
          <SearchBar />
          <main className="mt-14">{children}</main>
        </div>
      </body>
    </html>
  );
}
